### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by navels** [keenerd/gz-sort#10]
Any chance you'd be willing to switch to the less-restrictive MIT license?

**Comment by sjmulder** [comment]
I've contributed some code under the current license and I'm against such a change. GPL guarantees rights for end users.

**Comment by navels** [comment]
Gotcha.  I'd be curious to better understand what rights you're concerned with.  Asking with genuine curiosity, not because I plan on attacking your answer :-)  I don't fully understand all the legal in and outs of the different licenses.

**Comment by sjmulder** [comment]
I was hesitant about positing that comment because I don’t want to incite a flamewar, but you can’t simply change the license for a project that has accepted contributions. But mine were minor so I won’t object if the maintainer insists on a change.

Regarding the freedoms, GPL prevents closing the source to derived works. This is a restriction for vendors but a freedom for users because they are again free to inspect, modify and redistribute the source.

**Comment by navels** [comment]
I understand, yep.  In my case I'd like to use this internally, not to be redistributed or even the source included, just some python code making a system call to the binary.

However, I can't . . . I'm assuming because there is too much risk once a GPL-ed project is in our ecosystem that it could inadvertently be included in some other project inappropriately.

I'll hang around and see what @keenerd says.  Looks like the license can be changed if all the contributors (the two of you) agree.  Thanks.

**Comment by sjmulder** [comment]
But the GPL does not prevent you from using it internally. Is it company policy?

**Comment by navels** [comment]
Yes.
